# -*- coding: utf-8 -*-
# Copyright 2024 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function


__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the vyos_vrf module
"""

from ansible_collections.vyos.vyos.plugins.module_utils.network.vyos.argspec.bgp_global.bgp_global import (
    Bgp_globalArgs,
)
from ansible_collections.vyos.vyos.plugins.module_utils.network.vyos.argspec.ospfv2.ospfv2 import (
    Ospfv2Args,
)
from ansible_collections.vyos.vyos.plugins.module_utils.network.vyos.argspec.ospfv3.ospfv3 import (
    Ospfv3Args,
)
from ansible_collections.vyos.vyos.plugins.module_utils.network.vyos.argspec.static_routes.static_routes import (
    Static_routesArgs,
)


class VrfArgs(object):  # pylint: disable=R0903
    """The arg spec for the vyos_vrf module"""

    bgp_argument_spec = Bgp_globalArgs.argument_spec["config"]
    static_routes_argument_spec = Static_routesArgs.argument_spec["config"]
    ospfv2_argument_spec = Ospfv2Args.argument_spec["config"]
    ospfv3_argument_spec = Ospfv3Args.argument_spec["config"]

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "bind_to_all": {"type": "bool", "default": False},
                "instances": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"required": True, "type": "str"},
                        "description": {"type": "str"},
                        "disable": {
                            "aliases": ["disabled"],
                            "default": False,
                            "type": "bool",
                        },
                        "table_id": {"type": "int"},
                        "vni": {"type": "int"},
                        "address_family": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "afi": {
                                    "type": "str",
                                    "choices": ["ipv4", "ipv6"],
                                },
                                "disable_forwarding": {"type": "bool", "default": False},
                                "nht_no_resolve_via_default": {"type": "bool", "default": False},
                                "route_maps": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "rm_name": {"type": "str", "required": True},
                                        "protocol": {
                                            "type": "str",
                                            "choices": [
                                                "any",
                                                "babel",
                                                "bgp",
                                                "connected",
                                                "eigrp",
                                                "isis",
                                                "kernel",
                                                "ospf",
                                                "rip",
                                                "static",
                                                "table",
                                            ],
                                        },
                                    },
                                },
                            },
                        },
                        "protocols": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "bgp": bgp_argument_spec,
                                "ospf": ospfv2_argument_spec,
                                "ospfv3": ospfv3_argument_spec,
                                "static": static_routes_argument_spec,
                            },
                        },
                    },
                },
            },
        },
        "state": {
            "type": "str",
            "choices": [
                "deleted",
                "merged",
                "replaced",
                "overridden",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
        "running_config": {"type": "str"},
    }  # pylint: disable=C0301
