# -*- coding: utf-8 -*-
# Copyright 2024 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function


__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the vyos_vrf module
"""


class VrfArgs(object):  # pylint: disable=R0903
    """The arg spec for the vyos_vrf module"""

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "bind_to_all": {"type": "bool", "default": False},
                "instances": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"required": True, "type": "str"},
                        "description": {"type": "str"},
                        "disable": {
                            "aliases": ["disabled"],
                            "default": False,
                            "type": "bool",
                        },
                        "table_id": {"type": "int"},
                        "vni": {"type": "int"},
                        "address_family": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "afi": {
                                    "type": "str",
                                    "choices": ["ipv4", "ipv6"],
                                },
                                "disable_forwarding": {"type": "bool", "default": False},
                                "no_resolve_via_default": {"type": "bool", "default": False},
                            },
                        },
                    },
                },
            },
        },
        "state": {
            "type": "str",
            "choices": [
                "deleted",
                "merged",
                "replaced",
                "overridden",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
        "running_config": {"type": "str"},
    }  # pylint: disable=C0301
