# -*- coding: utf-8 -*-
# Copyright 2024 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function


__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the vyos_vrrp module
"""


class VrrpArgs(object):  # pylint: disable=R0903
    """The arg spec for the vyos_vrrp module"""

    argument_spec = {
        "config": {
            "type": "dict",
            "required": False,
            "options": {
                "disable": {"type": "bool", "default": False},
                "virtual_servers": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"type": "str", "required": True},
                        "address": {"type": "str"},
                        "algorithm": {"type": "str"},
                        "delay_loop": {"type": "int"},
                        "forward_method": {"type": "str", "choices": ["direct", "nat"]},
                        "fwmark": {"type": "str"},
                        "persistence_timeout": {"type": "str"},
                        "port": {"type": "int"},
                        "protocol": {"type": "str", "choices": ["tcp", "udp"]},
                        "real_servers": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "address": {"type": "str", "required": True},
                                "port": {"type": "int"},
                                "health_check_script": {"type": "str"},
                            },
                        },
                    },
                },
                "vrrp": {
                    "type": "dict",
                    "options": {
                        "global_parameters": {
                            "type": "dict",
                            "options": {
                                "garp": {
                                    "type": "dict",
                                    "options": {
                                        "interval": {"type": "int"},
                                        "master_delay": {"type": "int"},
                                        "master_refresh": {"type": "int"},
                                        "master_refresh_repeat": {"type": "int"},
                                        "master_repeat": {"type": "int"},
                                    },
                                },
                                "startup_delay": {"type": "int"},
                                "version": {"type": "str"},
                            },
                        },
                        "groups": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "name": {"type": "str", "required": True},
                                "address": {"type": "str"},
                                "advertise_interval": {"type": "int"},
                                "authentication": {
                                    "type": "dict",
                                    "options": {
                                        "password": {"type": "str", "no_log": True},
                                        "type": {"type": "str"},
                                    },
                                },
                                "description": {"type": "str"},
                                "disable": {"type": "bool", "default": False},
                                "excluded_address": {"type": "list", "elements": "str"},
                                "garp": {
                                    "type": "dict",
                                    "options": {
                                        "interval": {"type": "int"},
                                        "master_delay": {"type": "int"},
                                        "master_refresh": {"type": "int"},
                                        "master_refresh_repeat": {"type": "int"},
                                        "master_repeat": {"type": "int"},
                                    },
                                },
                                "health_check": {
                                    "type": "dict",
                                    "options": {
                                        "failure_count": {"type": "int"},
                                        "interval": {"type": "int"},
                                        "ping": {"type": "str"},
                                        "script": {"type": "str"},
                                    },
                                },
                                "hello_source_address": {"type": "str"},
                                "interface": {"type": "str"},
                                "no_preempt": {"type": "bool"},
                                "peer_address": {"type": "str"},
                                "preempt_delay": {"type": "int"},
                                "priority": {"type": "int"},
                                "rfc3768_compatibility": {"type": "bool"},
                                "track": {
                                    "type": "dict",
                                    "options": {
                                        "exclude_vrrp_interface": {"type": "bool"},
                                        "interface": {"type": "list", "elements": "str"},
                                    },
                                },
                                "transition_script": {
                                    "type": "dict",
                                    "options": {
                                        "backup": {"type": "str"},
                                        "fault": {"type": "str"},
                                        "master": {"type": "str"},
                                        "stop": {"type": "str"},
                                    },
                                },
                                "vrid": {"type": "int", "required": True},
                            },
                        },
                        "snmp": {"type": "bool"},
                        "sync_groups": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "name": {"type": "str", "required": True},
                                "health_check": {
                                    "type": "dict",
                                    "options": {
                                        "failure_count": {"type": "int"},
                                        "interval": {"type": "int"},
                                        "ping": {"type": "str"},
                                        "script": {"type": "str"},
                                    },
                                },
                                "member": {"type": "list", "elements": "str"},
                                "transition_script": {
                                    "type": "dict",
                                    "options": {
                                        "backup": {"type": "str"},
                                        "fault": {"type": "str"},
                                        "master": {"type": "str"},
                                        "stop": {"type": "str"},
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
        "state": {
            "type": "str",
            "choices": [
                "deleted",
                "merged",
                "purged",
                "replaced",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
        "running_config": {"type": "str"},
    }  # pylint: disable=C0301
