---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=2.5.1"
license_file: LICENSE
name: vyos
description: Ansible Network Collection for VYOS devices.
namespace: vyos
readme: README.md
repository: https://github.com/ansible-collections/vyos.vyos
issues: https://github.com/ansible-collections/vyos.vyos/issues
tags: [vyos, networking]
version: 4.0.3-dev
