---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: vyos
namespace: vyos
readme: README.rst
repository: https://github.com/ansible-collections/vyos
