# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the vyos_logging_global module
"""


class Logging_globalArgs(object):  # pylint: disable=R0903
    """The arg spec for the vyos_logging_global module
    """

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "console_params": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "facility": {
                            "type": "str",
                            "choices": [
                                "all",
                                "auth",
                                "authpriv",
                                "cron",
                                "daemon",
                                "kern",
                                "lpr",
                                "mail",
                                "mark",
                                "news",
                                "protocols",
                                "security",
                                "syslog",
                                "user",
                                "uucp",
                                "local0",
                                "local1",
                                "local2",
                                "local3",
                                "local4",
                                "local5",
                                "local6",
                                "local7",
                            ],
                        },
                        "level": {
                            "type": "str",
                            "choices": [
                                "emerg",
                                "alert",
                                "crit",
                                "err",
                                "warning",
                                "notice",
                                "info",
                                "debug",
                                "all",
                            ],
                        },
                    },
                },
                "files": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "path": {"type": "str"},
                        "archive": {
                            "type": "dict",
                            "options": {
                                "file_num": {"type": "int"},
                                "size": {"type": "int"},
                            },
                        },
                        "params": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "facility": {
                                    "type": "str",
                                    "choices": [
                                        "all",
                                        "auth",
                                        "authpriv",
                                        "cron",
                                        "daemon",
                                        "kern",
                                        "lpr",
                                        "mail",
                                        "mark",
                                        "news",
                                        "protocols",
                                        "security",
                                        "syslog",
                                        "user",
                                        "uucp",
                                        "local0",
                                        "local1",
                                        "local2",
                                        "local3",
                                        "local4",
                                        "local5",
                                        "local6",
                                        "local7",
                                    ],
                                },
                                "level": {
                                    "type": "str",
                                    "choices": [
                                        "emerg",
                                        "alert",
                                        "crit",
                                        "err",
                                        "warning",
                                        "notice",
                                        "info",
                                        "debug",
                                        "all",
                                    ],
                                },
                            },
                        },
                    },
                },
                "global_params": {
                    "elements": "dict",
                    "options": {
                        "archive": {
                            "type": "dict",
                            "options": {
                                "file_num": {"type": "int"},
                                "size": {"type": "int"},
                            },
                        },
                        "params": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "facility": {
                                    "type": "str",
                                    "choices": [
                                        "all",
                                        "auth",
                                        "authpriv",
                                        "cron",
                                        "daemon",
                                        "kern",
                                        "lpr",
                                        "mail",
                                        "mark",
                                        "news",
                                        "protocols",
                                        "security",
                                        "syslog",
                                        "user",
                                        "uucp",
                                        "local0",
                                        "local1",
                                        "local2",
                                        "local3",
                                        "local4",
                                        "local5",
                                        "local6",
                                        "local7",
                                    ],
                                },
                                "level": {
                                    "type": "str",
                                    "choices": [
                                        "emerg",
                                        "alert",
                                        "crit",
                                        "err",
                                        "warning",
                                        "notice",
                                        "info",
                                        "debug",
                                        "all",
                                    ],
                                },
                            },
                        },
                        "marker_interval": {"type": "int"},
                        "preserve_fqdn": {"type": "bool"},
                    },
                },
                "hosts": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "params": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "port": {"type": "int"},
                                "facility": {
                                    "type": "str",
                                    "choices": [
                                        "all",
                                        "auth",
                                        "authpriv",
                                        "cron",
                                        "daemon",
                                        "kern",
                                        "lpr",
                                        "mail",
                                        "mark",
                                        "news",
                                        "protocols",
                                        "security",
                                        "syslog",
                                        "user",
                                        "uucp",
                                        "local0",
                                        "local1",
                                        "local2",
                                        "local3",
                                        "local4",
                                        "local5",
                                        "local6",
                                        "local7",
                                    ],
                                },
                                "level": {
                                    "type": "str",
                                    "choices": [
                                        "emerg",
                                        "alert",
                                        "crit",
                                        "err",
                                        "warning",
                                        "notice",
                                        "info",
                                        "debug",
                                        "all",
                                    ],
                                },
                                "protocol": {
                                    "type": "str",
                                    "choices": ["udp", "tcp"],
                                },
                            },
                        },
                        "hostname": {"type": "str"},
                    },
                },
                "users": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "username": {"type": "str"},
                        "params": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "facility": {
                                    "type": "str",
                                    "choices": [
                                        "all",
                                        "auth",
                                        "authpriv",
                                        "cron",
                                        "daemon",
                                        "kern",
                                        "lpr",
                                        "mail",
                                        "mark",
                                        "news",
                                        "protocols",
                                        "security",
                                        "syslog",
                                        "user",
                                        "uucp",
                                        "local0",
                                        "local1",
                                        "local2",
                                        "local3",
                                        "local4",
                                        "local5",
                                        "local6",
                                        "local7",
                                    ],
                                },
                                "level": {
                                    "type": "str",
                                    "choices": [
                                        "emerg",
                                        "alert",
                                        "crit",
                                        "err",
                                        "warning",
                                        "notice",
                                        "info",
                                        "debug",
                                        "all",
                                    ],
                                },
                            },
                        },
                    },
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "parsed",
                "rendered",
            ],
            "default": "merged",
            "type": "str",
        },
    }  # pylint: disable=C0301
