# -*- coding: utf-8 -*-
# Copyright 2026 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function


__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the vyos_vpn_ipsec_s2s module
"""


class Vpn_ipsec_s2sArgs(object):  # pylint: disable=R0903
    """The arg spec for the vyos_vpn_ipsec_s2s module"""

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "peer": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"type": "str", "required": True},
                        "disable": {"type": "bool"},
                        "authentication": {
                            "type": "dict",
                            "options": {
                                "local_id": {"type": "str"},
                                "ppk": {
                                    "type": "dict",
                                    "options": {
                                        "id": {"type": "str"},
                                        "required": {"type": "bool"},
                                    },
                                },
                                "rsa": {
                                    "type": "dict",
                                    "options": {
                                        "local_key": {"type": "str", "no_log": True},
                                        "passphrase": {"type": "str", "no_log": True},
                                        "remote_key": {"type": "str", "no_log": True},
                                    },
                                },
                                "x509": {
                                    "type": "dict",
                                    "options": {
                                        "certificate": {"type": "str"},
                                        "passphrase": {"type": "str", "no_log": True},
                                        "ca_certificate": {
                                            "type": "list",
                                            "elements": "str",
                                        },
                                    },
                                },
                                "mode": {
                                    "type": "str",
                                    "choices": [
                                        "pre-shared-secret",
                                        "rsa",
                                        "x509",
                                    ],
                                },
                                "remote_id": {"type": "str"},
                                "use_x509_id": {"type": "bool"},
                            },
                        },
                        "childless": {
                            "type": "str",
                            "choices": ["allow", "prefer", "force", "never"],
                        },
                        "connection_type": {
                            "type": "str",
                            "choices": ["initiate", "trap", "none"],
                        },
                        "default_esp_group": {"type": "str"},
                        "description": {"type": "str"},
                        "dhcp_interface": {"type": "str"},
                        "force_udp_encapsulation": {"type": "bool"},
                        "ike_group": {"type": "str"},
                        "ikev2_reauth": {
                            "type": "str",
                            "choices": ["yes", "no", "inherit"],
                        },
                        "local_address": {"type": "str"},
                        "remote_address": {"type": "list", "elements": "str"},
                        "replay_window": {"type": "int"},
                        "tunnel": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "tunnel_id": {"type": "int", "required": True},
                                "disable": {"type": "bool"},
                                "esp_group": {"type": "str"},
                                "local": {
                                    "type": "dict",
                                    "options": {
                                        "port": {"type": "int"},
                                        "prefix": {
                                            "type": "list",
                                            "elements": "str",
                                        },
                                    },
                                },
                                "protocol": {"type": "str"},
                                "priority": {"type": "int"},
                                "remote": {
                                    "type": "dict",
                                    "options": {
                                        "port": {"type": "int"},
                                        "prefix": {
                                            "type": "list",
                                            "elements": "str",
                                        },
                                    },
                                },
                            },
                        },
                        "virtual_address": {"type": "list", "elements": "str"},
                        "vti": {
                            "type": "dict",
                            "options": {
                                "bind": {"type": "str"},
                                "esp_group": {"type": "str"},
                                "traffic_selector": {
                                    "type": "dict",
                                    "options": {
                                        "local": {
                                            "type": "dict",
                                            "options": {
                                                "prefix": {
                                                    "type": "list",
                                                    "elements": "str",
                                                },
                                            },
                                        },
                                        "remote": {
                                            "type": "dict",
                                            "options": {
                                                "prefix": {
                                                    "type": "list",
                                                    "elements": "str",
                                                },
                                            },
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
