# -*- coding: utf-8 -*-
# Copyright 2024 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function


__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the vyos_nat module
"""


class NatArgs(object):  # pylint: disable=R0903
    """The arg spec for the vyos_nat module"""

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "cgnat": {
                    "type": "dict",
                    "options": {
                        "log_allocation": {
                            "type": "bool",
                        },
                        "pool": {
                            "type": "dict",
                            "options": {
                                "external": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "name": {
                                            "type": "str",
                                            "required": True,
                                        },
                                        "external_port_range": {
                                            "type": "str",
                                        },
                                        "per_user_limit_port": {
                                            "type": "int",
                                        },
                                        "ranges": {
                                            "type": "list",
                                            "elements": "str",
                                        },
                                    },
                                },
                                "internal": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "name": {
                                            "type": "str",
                                            "required": True,
                                        },
                                        "ranges": {
                                            "type": "list",
                                            "elements": "str",
                                        },
                                    },
                                },
                            },
                        },
                        "rule": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "id": {
                                    "type": "int",
                                    "required": True,
                                },
                                "source": {
                                    "type": "dict",
                                    "options": {
                                        "pool": {
                                            "type": "str",
                                        },
                                    },
                                },
                                "translation": {
                                    "type": "dict",
                                    "options": {
                                        "pool": {
                                            "type": "str",
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
                "destination": {
                    "type": "dict",
                    "options": {
                        "rule": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "id": {
                                    "type": "int",
                                    "required": True,
                                },
                                "description": {
                                    "type": "str",
                                },
                                "destination": {
                                    "type": "dict",
                                    "options": {
                                        "address": {
                                            "type": "str",
                                        },
                                        "fqdn": {
                                            "type": "str",
                                        },
                                        "group": {
                                            "type": "dict",
                                            "options": {
                                                "address-group": {
                                                    "type": "str",
                                                },
                                                "domain-group": {
                                                    "type": "str",
                                                },
                                                "mac-group": {
                                                    "type": "str",
                                                },
                                                "network-group": {
                                                    "type": "str",
                                                },
                                                "port-group": {
                                                    "type": "str",
                                                },
                                            },
                                        },
                                        "port": {
                                            "type": "str",
                                        },
                                        "protocol": {
                                            "type": "str",
                                        },
                                        "exclude": {
                                            "type": "bool",
                                        },
                                        "log": {
                                            "type": "bool",
                                        },
                                        "disable": {
                                            "type": "bool",
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "deleted",
                "merged",
                "overridden",
                "replaced",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
