# -*- coding: utf-8 -*-
# Copyright 2026 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function


__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the vyos_vpn_ipsec module
"""


class Vpn_ipsecArgs(object):  # pylint: disable=R0903
    """The arg spec for the vyos_vpn_ipsec module"""

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "ike_group": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"type": "str", "required": True},
                        "close_action": {
                            "type": "str",
                            "choices": ["none", "trap", "start"],
                        },
                        "dead_peer_detection": {
                            "type": "dict",
                            "options": {
                                "action": {
                                    "type": "str",
                                    "choices": ["trap", "clear", "restart"],
                                },
                                "interval": {"type": "int"},
                                "timeout": {"type": "int"},
                            },
                        },
                        "disable_mobike": {"type": "bool"},
                        "ikev2_reauth": {"type": "bool"},
                        "key_exchange": {
                            "type": "str",
                            "choices": ["ikev1", "ikev2"],
                        },
                        "lifetime": {"type": "int"},
                        "mode": {"type": "str", "choices": ["main", "aggressive"]},
                        "proposal": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "proposal_id": {"type": "int"},
                                "dh_group": {"type": "int"},
                                "encryption": {"type": "str"},
                                "hash": {"type": "str"},
                                "prf": {"type": "str"},
                            },
                        },
                    },
                },
                "esp_group": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"type": "str", "required": True},
                        "compression": {"type": "bool"},
                        "disable_rekey": {"type": "bool"},
                        "life_bytes": {"type": "int"},
                        "life_packets": {"type": "int"},
                        "lifetime": {"type": "int"},
                        "mode": {
                            "type": "str",
                            "choices": ["tunnel", "transport"],
                        },
                        "pfs": {"type": "str"},
                        "proposal": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "proposal_id": {"type": "int"},
                                "encryption": {"type": "str"},
                                "hash": {"type": "str"},
                            },
                        },
                    },
                },
                "authentication": {
                    "type": "dict",
                    "options": {
                        "psk": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "name": {"type": "str", "required": True},
                                "id": {"type": "list", "elements": "str"},
                                "dhcp_interface": {
                                    "type": "list",
                                    "elements": "str",
                                },
                                "secret": {"type": "str", "no_log": True},
                                "secret_type": {
                                    "type": "str",
                                    "choices": ["base64", "hex", "plaintext"],
                                },
                            },
                        },
                        "ppk": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "name": {"type": "str", "required": True},
                                "id": {"type": "list", "elements": "str"},
                                "secret": {"type": "str", "no_log": True},
                                "secret_type": {
                                    "type": "str",
                                    "choices": ["base64", "hex", "plaintext"],
                                },
                            },
                        },
                    },
                },
                "profile": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"type": "str", "required": True},
                        "authentication": {
                            "type": "dict",
                            "options": {
                                "mode": {
                                    "type": "str",
                                    "choices": ["pre-shared-secret"],
                                },
                                "pre_shared_secret": {"type": "str", "no_log": True},
                            },
                        },
                        "bind_tunnel": {"type": "list", "elements": "str"},
                        "disable": {"type": "bool"},
                        "esp_group": {"type": "str"},
                        "ike_group": {"type": "str"},
                    },
                },
                "interface": {"type": "list", "elements": "str"},
                "log": {
                    "type": "dict",
                    "options": {
                        "level": {"type": "int"},
                        "subsystem": {
                            "type": "list",
                            "elements": "str",
                        },
                    },
                },
                "options": {
                    "type": "dict",
                    "options": {
                        "disable_route_autoinstall": {"type": "bool"},
                        "flexvpn": {"type": "bool"},
                        "interface": {"type": "str"},
                        "retransmission": {
                            "type": "dict",
                            "options": {
                                "attempts": {"type": "int"},
                                "base": {"type": "float"},
                                "timeout": {"type": "int"},
                            },
                        },
                        "virtual_ip": {"type": "bool"},
                    },
                },
                "disable_uniqreqids": {"type": "bool"},
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
