# -*- coding: utf-8 -*-
# Copyright 2026 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function


__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the vyos_vpn_ipsec module
"""


class Vpn_ipsecArgs(object):  # pylint: disable=R0903
    """The arg spec for the vyos_vpn_ipsec module"""

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "ike_group": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"type": "str", "required": True},
                        "close_action": {
                            "type": "str",
                            "choices": ["none", "trap", "start"],
                        },
                        "dead_peer_detection": {
                            "type": "dict",
                            "options": {
                                "action": {
                                    "type": "str",
                                    "choices": ["trap", "clear", "restart"],
                                },
                                "interval": {"type": "int"},
                                "timeout": {"type": "int"},
                            },
                        },
                        "disable_mobike": {"type": "bool"},
                        "ikev2_reauth": {"type": "bool"},
                        "key_exchange": {
                            "type": "str",
                            "choices": ["ikev1", "ikev2"],
                        },
                        "lifetime": {"type": "int"},
                        "mode": {"type": "str", "choices": ["main", "aggressive"]},
                        "proposal": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "proposal_id": {"type": "int"},
                                "dh_group": {
                                    "type": "int",
                                    "choices": [
                                        1,
                                        2,
                                        5,
                                        14,
                                        15,
                                        16,
                                        17,
                                        18,
                                        19,
                                        20,
                                        21,
                                        22,
                                        23,
                                        24,
                                        25,
                                        26,
                                        27,
                                        28,
                                        29,
                                        30,
                                        31,
                                        32,
                                    ],
                                },
                                "encryption": {
                                    "type": "str",
                                    "choices": [
                                        "null",
                                        "aes128",
                                        "aes192",
                                        "aes256",
                                        "aes128ctr",
                                        "aes192ctr",
                                        "aes256ctr",
                                        "aes128ccm64",
                                        "aes192ccm64",
                                        "aes256ccm64",
                                        "aes128ccm96",
                                        "aes192ccm96",
                                        "aes256ccm96",
                                        "aes128ccm128",
                                        "aes192ccm128",
                                        "aes256ccm128",
                                        "aes128gcm64",
                                        "aes192gcm64",
                                        "aes256gcm64",
                                        "aes128gcm96",
                                        "aes192gcm96",
                                        "aes256gcm96",
                                        "aes128gcm128",
                                        "aes192gcm128",
                                        "aes256gcm128",
                                        "aes128gmac",
                                        "aes192gmac",
                                        "aes256gmac",
                                        "3des",
                                        "blowfish128",
                                        "blowfish192",
                                        "blowfish256",
                                        "camellia128",
                                        "camellia192",
                                        "camellia256",
                                        "camellia128ctr",
                                        "camellia192ctr",
                                        "camellia256ctr",
                                        "camellia128ccm64",
                                        "camellia192ccm64",
                                        "camellia256ccm64",
                                        "camellia128ccm96",
                                        "camellia192ccm96",
                                        "camellia256ccm96",
                                        "camellia128ccm128",
                                        "camellia192ccm128",
                                        "camellia256ccm128",
                                        "serpent128",
                                        "serpent192",
                                        "serpent256",
                                        "twofish128",
                                        "twofish192",
                                        "twofish256",
                                        "cast128",
                                        "chacha20poly1305",
                                    ],
                                },
                                "hash": {
                                    "type": "str",
                                    "choices": [
                                        "md5",
                                        "md5_128",
                                        "sha1",
                                        "sha1_160",
                                        "sha256",
                                        "sha256_96",
                                        "sha384",
                                        "sha512",
                                        "aesxcbc",
                                        "aescmac",
                                        "aes128gmac",
                                        "aes192gmac",
                                        "aes256gmac",
                                    ],
                                },
                                "prf": {
                                    "type": "str",
                                    "choices": [
                                        "prfmd5",
                                        "prfsha1",
                                        "prfaesxcbc",
                                        "prfaescmac",
                                        "prfsha256",
                                        "prfsha384",
                                        "prfsha512",
                                    ],
                                },
                            },
                        },
                    },
                },
                "esp_group": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"type": "str", "required": True},
                        "compression": {"type": "bool"},
                        "disable_rekey": {"type": "bool"},
                        "life_bytes": {"type": "int"},
                        "life_packets": {"type": "int"},
                        "lifetime": {"type": "int"},
                        "mode": {
                            "type": "str",
                            "choices": ["tunnel", "transport"],
                        },
                        "pfs": {
                            "type": "str",
                            "choices": [
                                "enable",
                                "disable",
                                "dh-group1",
                                "dh-group2",
                                "dh-group5",
                                "dh-group14",
                                "dh-group15",
                                "dh-group16",
                                "dh-group17",
                                "dh-group18",
                                "dh-group19",
                                "dh-group20",
                                "dh-group21",
                                "dh-group22",
                                "dh-group23",
                                "dh-group24",
                                "dh-group25",
                                "dh-group26",
                                "dh-group27",
                                "dh-group28",
                                "dh-group29",
                                "dh-group30",
                                "dh-group31",
                                "dh-group32",
                            ],
                        },
                        "proposal": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "proposal_id": {"type": "int"},
                                "encryption": {
                                    "type": "str",
                                    "choices": [
                                        "null",
                                        "aes128",
                                        "aes192",
                                        "aes256",
                                        "aes128ctr",
                                        "aes192ctr",
                                        "aes256ctr",
                                        "aes128ccm64",
                                        "aes192ccm64",
                                        "aes256ccm64",
                                        "aes128ccm96",
                                        "aes192ccm96",
                                        "aes256ccm96",
                                        "aes128ccm128",
                                        "aes192ccm128",
                                        "aes256ccm128",
                                        "aes128gcm64",
                                        "aes192gcm64",
                                        "aes256gcm64",
                                        "aes128gcm96",
                                        "aes192gcm96",
                                        "aes256gcm96",
                                        "aes128gcm128",
                                        "aes192gcm128",
                                        "aes256gcm128",
                                        "aes128gmac",
                                        "aes192gmac",
                                        "aes256gmac",
                                        "3des",
                                        "blowfish128",
                                        "blowfish192",
                                        "blowfish256",
                                        "camellia128",
                                        "camellia192",
                                        "camellia256",
                                        "camellia128ctr",
                                        "camellia192ctr",
                                        "camellia256ctr",
                                        "camellia128ccm64",
                                        "camellia192ccm64",
                                        "camellia256ccm64",
                                        "camellia128ccm96",
                                        "camellia192ccm96",
                                        "camellia256ccm96",
                                        "camellia128ccm128",
                                        "camellia192ccm128",
                                        "camellia256ccm128",
                                        "serpent128",
                                        "serpent192",
                                        "serpent256",
                                        "twofish128",
                                        "twofish192",
                                        "twofish256",
                                        "cast128",
                                        "chacha20poly1305",
                                    ],
                                },
                                "hash": {
                                    "type": "str",
                                    "choices": [
                                        "md5",
                                        "md5_128",
                                        "sha1",
                                        "sha1_160",
                                        "sha256",
                                        "sha256_96",
                                        "sha384",
                                        "sha512",
                                        "aesxcbc",
                                        "aescmac",
                                        "aes128gmac",
                                        "aes192gmac",
                                        "aes256gmac",
                                    ],
                                },
                            },
                        },
                    },
                },
                "authentication": {
                    "type": "dict",
                    "options": {
                        "psk": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "name": {"type": "str", "required": True},
                                "id": {"type": "list", "elements": "str"},
                                "dhcp_interface": {
                                    "type": "list",
                                    "elements": "str",
                                },
                                "secret": {"type": "str", "no_log": True},
                                "secret_type": {
                                    "type": "str",
                                    "choices": ["base64", "hex", "plaintext"],
                                },
                            },
                        },
                        "ppk": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "name": {"type": "str", "required": True},
                                "id": {"type": "list", "elements": "str"},
                                "secret": {"type": "str", "no_log": True},
                                "secret_type": {
                                    "type": "str",
                                    "choices": ["base64", "hex", "plaintext"],
                                },
                            },
                        },
                    },
                },
                "profile": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "name": {"type": "str", "required": True},
                        "authentication": {
                            "type": "dict",
                            "options": {
                                "mode": {
                                    "type": "str",
                                    "choices": ["pre-shared-secret"],
                                },
                                "pre_shared_secret": {
                                    "type": "str",
                                    "no_log": True,
                                },
                            },
                        },
                        "bind_tunnel": {"type": "list", "elements": "str"},
                        "disable": {"type": "bool"},
                        "esp_group": {"type": "str"},
                        "ike_group": {"type": "str"},
                    },
                },
                "interface": {"type": "list", "elements": "str"},
                "log": {
                    "type": "dict",
                    "options": {
                        "level": {"type": "int", "choices": [0, 1, 2]},
                        "subsystem": {
                            "type": "list",
                            "elements": "str",
                            "choices": [
                                "dmn",
                                "mgr",
                                "ike",
                                "chd",
                                "job",
                                "cfg",
                                "knl",
                                "net",
                                "asn",
                                "enc",
                                "lib",
                                "esp",
                                "tls",
                                "tnc",
                                "imc",
                                "imv",
                                "pts",
                                "any",
                            ],
                        },
                    },
                },
                "options": {
                    "type": "dict",
                    "options": {
                        "disable_route_autoinstall": {"type": "bool"},
                        "flexvpn": {"type": "bool"},
                        "interface": {"type": "str"},
                        "retransmission": {
                            "type": "dict",
                            "options": {
                                "attempts": {"type": "int"},
                                "base": {"type": "float"},
                                "timeout": {"type": "int"},
                            },
                        },
                        "virtual_ip": {"type": "bool"},
                    },
                },
                "disable_uniqreqids": {"type": "bool"},
            },
        },
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
