---
minor_changes:
  - vyos_config - Add `smart` match mode, which enforces the supplied configuration as the desired end-state, generating delete commands for existing config not present in the candidate.
