# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the vyos_ntp module
"""


class NtpArgs(object):  # pylint: disable=R0903
    """The arg spec for the vyos_ntp module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "allow_clients": {
                    "type": "dict",
                    "options": {
                        "address": {"type": "list", "choices": ["Ip", "IPv6"]}
                    },
                },
                "listen_address": {"type": "str", "choices": ["Ip", "IPv6"]},
                "server": {
                    "type": "dict",
                    "options": {
                        "server_name": {
                            "type": "dict",
                            "options": {
                                "server_options": {
                                    "type": "list",
                                    "choices": [
                                        "noselect",
                                        "pool",
                                        "preempt",
                                        "prefer",
                                    ],
                                }
                            },
                        }
                    },
                },
            },
        }
    }  # pylint: disable=C0301
