#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2021 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for vyos_bgp_global
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = """
module: vyos_bgp_global
version_added: 1.3.0
short_description: BGP Global Resource Module.
description: 
- This module manages BGP global configuration of interfaces on devices running VYOS.
author: Gomathi Selvi Srinivasan (@GomathiselviS)
options:
  config:
    description: A dict of BGP global configuration for interfaces.
    type: dict
    suboptions:
      as_num:
        description:
        - AS number.
        type: int
        required: True
      aggregate_address:
        description:
          - BGP aggregate network.
        type: dict
        suboptions:
          address:
            description: BGP aggregate network.
            type: str
          as_set:
            description: Generate AS-set path information for this aggregate address.
            type: bool
          summary_only:
            description: Announce the aggregate summary network only.
            type: bool
      maximum_paths:
        description: BGP multipaths
        type: dict
        suboptions:
          path_type:
            description: BGP multipaths
            type: str
            choices: ['ebgp', 'ibgp']
          count:
            description: No. of paths.
            type: int
      neighbor:
        description: BGP neighbor
        type: dict
        suboptions:
          address:
            description: BGP neighbor address (v4/v6).
            type: str
          advertisement_interval:
            description: Minimum interval for sending routing updates.
            type: int
          allowas_in:
            description: Number of occurrences of AS number.
            type: int
          as_override:
            description:  AS for routes sent to this neighbor to be the local AS.
            type: bool
          attribute_unchanged:
            description: BGP attributes are sent unchanged.
            type: str
            choices: ['as_path', 'med', 'next_hop']
          capability:
            description: Advertise capabilities to this neighbor.
            type: dict
            suboptions:
              dynamic:
                description: Advertise dynamic capability to this neighbor.
                type: bool
              orf:
                description: Advertise ORF capability to this neighbor.
                type: str
                choices: ['send', 'receive']
          default_originiate:
            description: Send default route to this neighbor
            type: str
          description:
            description: description text
            type: str
          disable_capability_negotiation:
            description: Disbale capability negotiation with the neighbor
            type: bool
          disable_connected_check:
            description: Disable check to see if EBGP peer's address is a connected route.
            type: bool
          disable_send_community:
            description: Disable sending community attributes to this neighbor.
            type: str
            choices: ['extended', 'standard']
          distribute_list:
            description:  Access-list to filter route updates to/from this neighbor.
            type: list
            elements: dict
            suboptions:
              action:
                description:  Access-list to filter outgoing/incoming route updates to this neighbor
                type: str
                choices: ['export', 'import']
              acl:
                description: Acess-list number.
                type: int
          ebgp_multihop:
            description: Allow this EBGP neighbor to not be on a directly connected network. Specify
                         the number hops.
            type: int
          filter_list:
            description: As-path-list to filter route updates to/from this neighbor.
            type: list
            elements: dict
            suboptions:
              action:
                description: filter outgoing/incoming route updates
                type: str
                choices: ['export', 'import']
              path_list:
                description: As-path-list to filter
                type: str
          local_as:
            description: local as number not to be prepended to updates from EBGP peers
            type: int
          maximum_prefix:
            description:  Maximum number of prefixes to accept from this neighbor
               nexthop-self Nexthop for routes sent to this neighbor to be the local router.
            type: int
          nexthop-self:
            description:  Nexthop for routes sent to this neighbor to be the local router.
            type: bool
          override_capability:
            description: Ignore capability negotiation with specified neighbor.
            type: bool
          passive:
            description: Do not initiate a session with this neighbor
            type: bool
          password:
            description: BGP MD5 password
            type: str
          peer_group_name:
            description:  IPv4 peer group for this peer
            type: str
          peer_group:
            description: True if all the configs unde this neighbor key is for peer group template.
            type: bool
          port:
            description: Neighbor's BGP port
            type: int
          prefix_list:
            description: Prefix-list to filter route updates to/from this neighbor.
            type: list
            elements: dict
            suboptions:
              action:
                description: filter outgoing/incoming route updates
                type: str
                choices: ['export', 'import']
              prefix_list:
                description: Prefix-list to filter
                type: str
          remote_as:
            description: Neighbor BGP AS number
            type: int
          remove_private_as:
            description: Remove private AS numbers from AS path in outbound route updates
            type: bool
          route_map:
            description: Route-map to filter route updates to/from this neighbor.
            type: list
            elements: dict
            suboptions:
              action:
                description: filter outgoing/incoming route updates
                type: str
                choices: ['export', 'import']
              route_map:
                description: route-map to filter
                type: str
          route_reflector_client:
            description: Neighbor as a route reflector client
            type: bool
          route_server_client:
            description: Neighbor is route server client
            type: bool
          shutdown:
            description: Administratively shut down neighbor
            type: bool
          soft_reconfiguration:
            description: Soft reconfiguration for neighbor
            type: bool
          strict_capability_match:
            description: Enable strict capability negotiation
            type: bool
          unsupress_map:
            description:  Route-map to selectively unsuppress suppressed routes
            type: str
          update_source:
            description:  Source IP of routing updates
            type: str
          weight:
            description: Default weight for routes from this neighbor
            type: int
          ttl_security:
            description: Ttl security mechanism for this BGP peer
            type: int
          timers:
            description: Neighbor timers
            type: dict
            suboptions:
              connect:
                description: BGP connect timer for this neighbor.
                type: int
              holdtime:
                description: BGP hold timer for this neighbor
                type: int
              keepalive:
                description: BGP keepalive interval for this neighbor
                type: int
      network:
        description: BGP network
        type: list
        elements: dict
        suboptions:
          address:
            description: BGP network address
            type: str
          backdoor:
            description: Network as a backdoor route
            type: bool
          route_map:
            description: Route-map to modify route attributes
            type: str
      redistribute:
        description: Redistribute routes from other protocols into BGP
        type: list
        elements: dict
        suboptions:
          protocol:
            description: types of routes to be redistributed.
            type: str
            choices: ['connected', 'kernel', 'ospf', 'rip', 'static']
          route_map:
            description: Route map to filter redistributed routes
            type: str
          metric:
            description: Metric for redistributed routes.
            type: int
      timers:
        description: BGP protocol timers
        type: dict
        suboptions:
          keepalive:
            description: Keepalive interval
            type: int
          holdtime:
            description: Hold time interval
            type: int
      bgp_params:
        description: BGP parameters
        type: dict
        suboptions:
          always_compare_med:
            description: Always compare MEDs from different neighbors
            type: bool
          bestpath:
            description: Default bestpath selection mechanism
            type: dict
            suboptions:
              as_path:
                description: AS-path attribute comparison parameters
                type: str
                choices: ['confed', 'ignore']
              comapre_routerid:
                description: Compare the router-id for identical EBGP paths
                type: bool
              med:
                description: MED attribute comparison parameters
                type: str
                choices: ['confed', 'missing-as-worst']
          cluster_id:
            description: Route-reflector cluster-id
            type: str
          confederation:
            description: AS confederation parameters
            type: list
            elements: dict
            suboptions:
              identifier:
                description: Confederation AS identifier
                type: int
              peers:
                description: Peer ASs in the BGP confederation
                type: int
          dampening:
            description: Enable route-flap dampening
            type: dict
            suboptions:
              half_life:
                description: Half-life penalty in seconds
                type: int
              max_supress_time:
                description: Maximum duration to suppress a stable route
                type: int
              re_use:
                description: Time to start reusing a route 
                type: int
              start_supress_time:
                description: When to start suppressing a route
                type: int
          default:
            description: BGP defaults
            type: dict
            suboptions:
              local_pref:
                description: Default local preference
                type: int
              no_ipv4_unicast:
                description: Deactivate IPv4 unicast for a peer by default
                type: bool
          deterministic_med:
            description: Compare MEDs between different peers in the same AS
            type: bool
          disable_network_import_check:
            description:  Disable IGP route check for network statements
            type: bool
          distance:
            description: Administratives distances for BGP routes
            type: dict
            suboptions:
              global:
                description: Global administratives distances for BGP routes
                type: dict
                suboptions:
                  type:
                    description: Type of route
                    type: str
                    choices: ['external', 'internal', 'local']
                  value:
                    description: distance
                    type: int
                  prefix:
                    description: Administrative distance for a specific BGP prefix
                    type: int
          enforce_first_as:
            description: Require first AS in the path to match peer's AS
            type: bool
          graceful_restart:
            description: Maximum time to hold onto restarting peer's stale paths
            type: int
          log_neighbor_changes:
            description: Log neighbor up/down changes and reset reason
            type: bool
          no_client_to_client_reflection:
            description: Disable client to client route reflection
            type: bool
          no_fast_external_failover:
            description: Disable immediate sesison reset if peer's connected link goes down
            type: bool
          router_id:
            description: BGP router-id
            type: str
          scan_time:
            description: BGP route scanner interval
            type: int
  running_config:
    description:
    - This option is used only with state I(parsed).
    - The value of this option should be the output received from the IOS device by
      executing the command B(sh running-config | section ^interface).
    - The state I(parsed) reads the configuration from C(running_config) option and
      transforms it into Ansible structured data as per the resource module's argspec
      and the value is then returned in the I(parsed) key within the result.
  state:
    description:
      - The state the configuration should be left in.
    type: str
    choices:
    - merged
    - replaced
    - deleted
    - gathered
    - parsed
    - rendered
    - purged
    default: merged
"""

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vyos.vyos.plugins.module_utils.network.vyos.argspec.bgp_global.bgp_global import (
    Bgp_globalArgs,
)
from ansible_collections.vyos.vyos.plugins.module_utils.network.vyos.config.bgp_global.bgp_global import (
    Bgp_global,
)


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(
        argument_spec=Bgp_globalArgs.argument_spec,
        mutually_exclusive=[],
        required_if=[],
        supports_check_mode=False
    )

    result = Bgp_global(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
