name: Refresh the automation hub token
# the token expires every 30 days, so we need to refresh it
on:
    schedule:
        - cron: '0 12 1,15 * *' # run 12pm on the 1st and 15th of the month
    workflow_dispatch:

jobs:
    refresh:
        uses: ansible/team-devtools/.github/workflows/ah_token_refresh.yml@v22.5.0
        with:
            environment: release
        secrets:
            ah_token: ${{ secrets.AH_TOKEN }}
